export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS';
export const SAVE_ALL_CHARACTERS = 'SAVE_ALL_CHARACTERS';

/** pagination  */
export const GET_MORE_CHARACTERS = 'GET_MORE_CHARACTERS';
export const LAST_PAGE_SEARCH = 'LAST_PAGE_SEARCH';

/**search name  */
export const GET_NAME_CHARACTERS = 'GET_NAME_CHARACTERS';

/** Quotes */
export const GET_QUOTE_PROFILER = 'GET_QUOTE_PROFILER';
export const SET_QUOTE_PROFILER = 'SET_QUOTE_PROFILER';
export const CLEAN_QUOTE_PROFILER = 'CLEAN_QUOTE_PROFILER';

/** Episodes  */
export const GET_EPISODES = 'GET_EPISODES';
export const SET_EPISODES = 'SET_EPISODES';
