name: Breaking Bad
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install  and build
        run: npm install && npm run build

      - name: Deploy
          run: npm run deploy
          run: git config --global user.name "Julio-Freitas"
          run: git config --global user.email "julio.clf31@gmail.com"
